apiVersion: apps/v1
kind: Deployment

metadata:
  name: apprenticeship-exercise
  labels:
    app: apprenticeship-exercise

spec:
  selector:
    matchLabels:
      app: apprenticeship-exercise
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apprenticeship-exercise
    spec:
      containers:
        - name: apprenticeship-exercise
          image: us-central1-docker.pkg.dev/northern-gasket-403822/docker-repo/apprenticeship-exercise:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80