name: Exercise

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: '12'

    - name: build dockerfile
      run:  docker build -t response-app .

    - name: run application
      run:  sudo docker run -d -p 80:80 response-app

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@808117af9b4a1e57c4cb79dbcb2d25de5ea3c68d

  push_to_registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v4
    
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: beebecomebigbee/apprenticeship-exercise
    
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_to_GKE:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
    needs: push_to_registry
    steps:
      
      - name: Google auth
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: '${{ env.PROJECT_ID }}'
   
      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
      
      - name: Get GKE credentials
        run: |-
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone ${{ secrets.CLUSTER_ZONE }} --project ${{ env.PROJECT_ID }}

      - name: Pull from Docker Hub
        run: |-
          docker pull beebecomebigbee/apprenticeship-exercise:main

      - name: Push to Artifact Registry
        run: |-
          docker push \
          ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo/apprenticeship-exercise

      - name: Apply Deployment Server
        run: |-
          kubectl apply deployment app-deployment --image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo/apprenticeship-exercise

      - name: Expose Deployment Server
        run: |-
          kubectl expose deployment app-deployment \
          --type=LoadBalancer \
          --port 80 \
          --target-port 80