name: Exercise

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: build dockerfile
      run:  docker build -t response-app .

  #  - name: run tests
  #    uses: liatrio/github-actions/apprentice-action@master