name: Exercise

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: build dockerfile
      run:  docker build -t response-app .

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master